import { useState, useCallback, useEffect } from 'react';
import api from '../services/api';

export function useEstoque() {
  const [estoque, setEstoque] = useState({ filamentos: [], totalMetros: 0, historicoSaidas: [] });

  useEffect(() => {
    // The backend provides filamentos generated by the extrusao.
    api.get('/filamentos').then(response => {
      const filamentosBackend = response.data || [];
      const totalMetros = filamentosBackend.reduce((acc, f) => acc + (f.comprimento || 0), 0);
      setEstoque({
        filamentos: filamentosBackend,
        totalMetros,
        historicoSaidas: [] // Backend doesn't support tracking saidas yet
      });
    }).catch(error => console.error("Erro ao carregar estoque:", error));
  }, []);

  const entrada = useCallback((filamento) => {
    setEstoque(prev => ({
      ...prev,
      filamentos: [...prev.filamentos, filamento],
      totalMetros: prev.totalMetros + filamento.comprimento,
    }));
  }, []);

  const saida = useCallback(async (metros) => {
    try {
      await api.post(`/estoque/saida?metros=${metros}`);
      
      setEstoque(prev => {
        if (metros > prev.totalMetros) {
          throw new Error(`Estoque insuficiente! Solicitado: ${metros.toFixed(2)} m | Disponível: ${prev.totalMetros.toFixed(2)} m`);
        }

        let restante = metros;
        const rastreio = [];
        const newFilamentos = prev.filamentos.map(f => {
          if (restante <= 0) return f;
          const disponivel = f.comprimento; // assuming backend uses comprimento
          if (disponivel <= 0) return f;

          if (disponivel >= restante) {
            rastreio.push({ filamentoId: f.id, metros: restante, loteId: f.loteOrigemId || (f.lote ? f.lote.id : null) });
            const updated = { ...f, comprimento: disponivel - restante };
            restante = 0;
            return updated;
          } else {
            rastreio.push({ filamentoId: f.id, metros: disponivel, loteId: f.loteOrigemId || (f.lote ? f.lote.id : null) });
            restante -= disponivel;
            return { ...f, comprimento: 0 };
          }
        });

        const registro = {
          id: Date.now(),
          metros,
          rastreio,
          data: new Date().toISOString(),
        };

        return {
          filamentos: newFilamentos,
          totalMetros: prev.totalMetros - metros,
          historicoSaidas: [...prev.historicoSaidas, registro],
        };
      });
    } catch (error) {
      console.error("Erro ao realizar saída do estoque:", error);
      throw error;
    }
  }, []);

  const setAll = useCallback((newEstoque) => {
    setEstoque(newEstoque);
  }, []);

  return {
    filamentos: estoque.filamentos,
    totalMetros: estoque.totalMetros,
    historicoSaidas: estoque.historicoSaidas,
    entrada,
    saida,
    setAll,
  };
}
